---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: docs/README.md
  label: Homepage
- type: heading
  label: Data
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: npm run site:build
  publish_command: vuepress build -d .vuepress/dist
  preview_output_directory: ".vuepress/dist"
  output_directory: ".vuepress/dist"
